name: deploy
on:
  push:
    branches: ["main"]

jobs:
  deploy_prod:
    runs-on: [self-hosted]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Inspect files before checkout
        run: ls -la
      - name: show current directory before checkout
        run: pwd
      - name: Checkout
        uses: actions/checkout@v4
      - name: Inspect files after checkout
        run: ls -la
      - name: show current directory after checkout
        run: pwd
      - name: show all branches after checkout
        run: git branch -a
