name: deploy
on:
  push:
    branches: ["main"]

jobs:
  deploy_prod:
    runs-on: [self-hosted]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        run: /var/www/publish1.sh $PWD
