name: deploy
on:
  push:
    branches: ["main"]

jobs:
  deploy_prod:
    runs-on: [self-hosted]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - run: |
          "pnpm i"
          "npm run build"
          "rm -rf /var/www/biancademo1"
          "mv dist /var/www/biancademo1"
